package com.curio.notes.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF3B6EA5)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFD8E8FA)
val OnPrimaryContainerLight = Color(0xFF0B2A45)
val SecondaryLight = Color(0xFF5A6B7A)
val SecondaryContainerLight = Color(0xFFDCE8F2)
val OnSecondaryContainerLight = Color(0xFF1C3448)
val TertiaryLight = Color(0xFF3E7A52)
val TertiaryContainerLight = Color(0xFFD9EEDF)
val OnTertiaryContainerLight = Color(0xFF173F27)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFAF8F3)
val SurfaceLight = Color(0xFFFFFFFF)
val OnBackgroundLight = Color(0xFF1A1C1E)
val OnSurfaceLight = Color(0xFF1A1C1E)
val SurfaceVariantLight = Color(0xFFE8E4DA)
val OutlineLight = Color(0xFF73777F)

val PrimaryDark = Color(0xFF7CC7FF)
val OnPrimaryDark = Color(0xFF000000)
val PrimaryContainerDark = Color(0xFF0E3A52)
val OnPrimaryContainerDark = Color(0xFFD6EDFF)
val SecondaryDark = Color(0xFFB3C5D6)
val SecondaryContainerDark = Color(0xFF22303B)
val OnSecondaryContainerDark = Color(0xFFCFE3F2)
val TertiaryDark = Color(0xFF8FD0A8)
val TertiaryContainerDark = Color(0xFF1E3B2C)
val OnTertiaryContainerDark = Color(0xFFB9E6C8)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF000000)
val SurfaceDark = Color(0xFF121212)
val OnBackgroundDark = Color(0xFFECEDEF)
val OnSurfaceDark = Color(0xFFECEDEF)
val SurfaceVariantDark = Color(0xFF1E1E1E)
val OutlineDark = Color(0xFF3A3F45)
